'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Breakout_FINAL.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property About2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("About2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ballmulti() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ballmulti", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlockNorm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlockNorm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property BlockS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BlockS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blueBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Breakout() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Breakout", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Breakout1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Breakout1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cannon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cannon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cannonShots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cannonShots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Exit2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Exit2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FireBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FireBall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fireball1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fireball1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property howto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("howto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property howto2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("howto2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property HS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property metalBlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("metalBlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Narrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Narrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newgamePic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newgamePic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newgamePic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newgamePic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ocean() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ocean", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Options() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Options", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Options2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Options2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Pad2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Pad2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property shield() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shield", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property slime() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("slime", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Slow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Slow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stickyPad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stickyPad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Untitled_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Waves() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Waves", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Wide() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Wide", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yellowBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellowBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
